language: cpp

notifications:
  slack:
    'openmerc:hBVTzYE0ZqxSSDPazeSDrpzx#mercore'
  webhooks:
    urls:
      https://webhooks.gitter.im/e/0e8fdd1d54698a3f900d
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

compiler: clang

script:
  mkdir build
  cd build
  cmake ../
  make
